### ISSUE TITLE
Meta-programming tags in Rubi 4 possible?

### ISSUE THREAD

**Issue by axkr** [RuleBasedIntegration/Rubi-5#1]
Almost every Rubi 4 `Int`rule has the following structure

```mma
   lhs := rhs /; test 
```

where the `lhs` is something like ``Int[...,x_]`` and the `test` part contains something like `FreeQ[..] && ...`.

Can we have an additional "meta predicate"  `IntQ[<number>]` in the `test` part which contains the number of the `IfThenElse` left-hand-side?

The `IntQ` predicate itself always returns `True` and should have no effect on Rubi 4 evaluation.
The number (for example `112` ) can be read by an automatic Rubi 5 converter and get the parameter definition from a second file there we have a list of "rule numbers" and corresponding `lhs`:

```mma
{
 { 111, Int111[a_,b_,m_,x_] },
 { 112, Int112[a_,b_,m_,c_,d_,n_,x_] }
...

...
}
``` 

I think this can simplify the creation of an automatic converter from Rubi-4 to Rubi 5. 

The `Int` rules used by Rubi 4 can be extracted as described here 
- https://github.com/axkr/symja_android_library/wiki/Porting-Rubi-Integration-rules-to-Symja

and the Rubi 5 converter tool can use the "meta predicate"  `IntQ[n]` to do the rewriting to an `IfThenElse` rule set.

**Comment by AlbertRich** [comment]
Hi Axel,

The *Rubi* 5 function Int112 is for integrating expressions of the form `(a+b x)^m (c+d x)^n` wrt `x`.

All the *Rubi* 4 pattern matching rules for integrating expressions of that form are in the source file  [1.1.1.2 (a+b x)^m (c+d x)^n.nb](https://rulebasedintegration.org/NotebookRuleFiles/1%20Algebraic%20functions/1.1%20Binomial%20products/1.1.1%20Linear/1.1.1.2%20(a+b%20x)%5Em%20(c+d%20x)%5En.nb) available on *Rubi*'s website.

That's where your proposed Rubi 4 to 5 compiler should be looking.

Albert

**Comment by axkr** [comment]
You mean something like this:
- https://gist.github.com/axkr/ebc5c304dd4dee05e0b620ed73e74cdd

to extract the expressions and conditions from the right-hand-side of "one *.m file" and restructure the parts to an if-then-else rule?

**Comment by AlbertRich** [comment]
I don't understand how your "converter tool" produces Int*nnn* if-then-else functions.

In the Rubi-5 repository is the *Rubi* 4 file [1.2.1 (a+b x+c x^2)^p.m](https://github.com/RuleBasedIntegration/Rubi-5/blob/main/Rubi%204%20notebook%20files/1.2.1%20(a%2Bb%20x%2Bc%20x%5E2)%5Ep.m) which I manually compiled to produce the *Rubi* 5 function Int121.

Int121 is defined in [Rubi-5.m](https://github.com/RuleBasedIntegration/Rubi-5/blob/main/Rubi-5.m).

Please show me the function equivalent to my Int121 that your converter tool produces.
